#! /opt/rh/rh-python38/root/usr/bin/python3.8 -s
## an awful kludge to give our last very little bit of support for el7
# -*- coding: utf-8 -*-
import re
import sys
from nsiqcppstyle.nsiqcppstyle_exe import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
